WORLD_SIZE = 256
SEED = 42
SEA_LEVEL = 0.40
NOISE_SCALE = 100.0
OCTAVES = 6
PERSISTENCE = 0.5
LACUNARITY = 2.0
TERRAIN_THRESHOLDS = {"BEACH": 0.45, "PLAINS": 0.65, "HILLS": 0.80}
IMAGE_SIZE = (10.0, 10.0)
IMAGE_DPI = 150
TERRAIN_COLORS = {
    "OCEAN": "#1f77b4",
    "BEACH": "#e8d9a0",
    "PLAINS": "#4d9221",
    "HILLS": "#6b6b1f",
    "MOUNTAINS": "#7f7f7f",
}
FIGURE_TITLE = "Procedurally Generated Terrain"
OUTPUT_DIR = "output"
OUTPUT_FILENAME = "terrain_map.png"
METADATA_FILENAME = "metadata.json"
MAP_SOURCE = "PROCEDURAL"
ASSET_INPUT_DIR = "assets/input"
POPULATION_SEED_OFFSET = 9973
OBSTACLE_TERRAIN_TYPES = ["OCEAN", "MOUNTAINS"]
GENERATOR_VERSION = "1.5.0"

# Zone allocation (terrain -> graph bridge)
ZONE_GRID_SPACING = 24
ZONE_SAMPLE_RADIUS = 12
ZONE_POPULATION_SCALE = 20000
ZONE_MIN_POPULATION = 50
ZONE_JOB_MULTIPLIERS = {"PLAINS": 1.2, "BEACH": 0.8, "HILLS": 0.5, "MOUNTAINS": 0.2}
ZONE_KNN = 3
ZONE_CELL_SIZE_KM = 1.0
ZONE_TERRAIN_SPEED_KMH = {"PLAINS": 60.0, "BEACH": 40.0, "HILLS": 40.0, "MOUNTAINS": 20.0}
